### ISSUE TITLE
hardcoding paths is not a good idea!

### ISSUE THREAD

**Issue by anton-firmware** [ninjafrostpn/ROV-Dev#1]
```python
receiver = threading.Thread(target=receiving)
receiver.start()

path = r"D:\Users\Charles Turvey\Documents\Python\Projects\SavedImages\{:.0f}".format(time())
os.mkdir(path)
```
to improve usability across machines, you should probably ask the path to be input by the user when the script starts or something...

**Comment by ninjafrostpn** [comment]
This is simply a standin because it works on my computer and none else has had to work on it yet ;) sound familiar?

**Comment by ninjafrostpn** [comment]
Also probably a no to being input on start-up, because it can just spit out files into the folder where the code is run, but that does need to be something that is added... which I was going to do today XD

**Comment by anton-firmware** [comment]
yeah... but coding practice yo... anyway, I think this issue is resolved xD

**Comment by ninjafrostpn** [comment]
Oh, but it's not yet?

**Comment by ninjafrostpn** [comment]
Okay, now it's kinda fixed ;)

**Comment by anton-firmware** [comment]
;)
