### ISSUE TITLE
not enough minerals

### ISSUE THREAD

**Issue by anton-firmware** [ninjafrostpn/ROV-Dev#7]

**Comment by ninjafrostpn** [comment]
We intend to use lead weights as ballast, LEDs for lighting, and LiPos for a power source, as these are more dense, brighter, more conveniently shaped and more readily available than energy crystals. This is, therefore, a non-issue.

**Comment by ninjafrostpn** [comment]
Though they could be a nice-to-have in terms of aesthetics, this is not currently of utmost importance ;)
